TARGET = iphone:clang:latest:14.4
ARCHS = arm64

include $(THEOS)/makefiles/common.mk

TOOL_NAME = hello
meow_FILES = meow.c

include $(THEOS_MAKE_PATH)/tool.mk

SDKVERSION = 16.5
SYSROOT = /theos/sdks/iPhoneOS14.4.sdk
